# Generated by Django 5.1.1 on 2024-10-10 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Signup", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_joined",
        ),
    ]
