# Generated by Django 5.1.1 on 2024-10-10 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Signup", "0002_remove_customuser_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_superuser",
        ),
    ]
