# Generated by Django 5.1.1 on 2024-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Signup", "0003_remove_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="agree_to_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="body_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("victoria-secret-thin", "Victoria-Secret Thin"),
                    ("slim", "Slim"),
                    ("muscular", "Muscular"),
                    ("athletic", "Athletic"),
                    ("sumo-wrestler", "Sumo Wrestler"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customuser",
            name="receive_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
