# Generated by Django 5.1.1 on 2024-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Signup", "0004_customuser_age_customuser_agree_to_terms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="street",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="customuser",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
