# Generated by Django 5.1.1 on 2024-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Signup", "0007_alter_customuser_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
