# Generated by Django 5.1.1 on 2024-12-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0003_alter_customuser_intensity'),
        ('Signup', '0008_customuser_groups_customuser_is_staff_and_more'),
    ]

    operations = [
    ]
