# Generated by Django 5.1.1 on 2024-12-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("target_muscles", models.CharField(max_length=200)),
                ("difficulty_level", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.IntegerField()),
                ("calories_burned", models.IntegerField()),
                ("recommended_weight_range_min", models.FloatField()),
                ("recommended_weight_range_max", models.FloatField()),
                ("body_goal", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MySchedule.workouttype",
                    ),
                ),
            ],
        ),
    ]
