# Generated by Django 5.1.1 on 2024-12-04 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MySchedule", "0002_workoutselectionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutselectionlog",
            name="body_goal",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="workoutselectionlog",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="workoutselectionlog",
            name="selected_workouts",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workoutselectionlog",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_selection_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workoutselectionlog",
            name="user_intensity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
