# Generated by Django 5.1.1 on 2024-12-05 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MySchedule", "0003_alter_workoutselectionlog_body_goal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("target_nutrients", models.CharField(max_length=200)),
                ("calories_range_min", models.IntegerField()),
                ("calories_range_max", models.IntegerField()),
                ("body_goal", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="MealSelectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user_intensity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("body_goal", models.CharField(blank=True, max_length=30, null=True)),
                ("selected_meals", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_selection_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proteins", models.FloatField()),
                ("carbs", models.FloatField()),
                ("fats", models.FloatField()),
                ("total_calories", models.IntegerField()),
                ("body_goal", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MySchedule.mealtype",
                    ),
                ),
            ],
        ),
    ]
